version: '3.8'

services:
  db:
    image: postgres:15  # Versão explícita recomendada
    container_name: postgres-db
    environment:
      POSTGRES_DB: userSystem
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ndacps16
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
